---
- hosts: hashistack
  tasks:
    - name: install directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,g=rwx,o=rw"
      with_items:
        - "/tmp/monkey1"
        - "/tmp/monkey2"
        - "/tmp/monkey3"


    # Install HashiStack
    - name: import the hashicorp apt key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      # become: true

    - name: Get distribution info
      command: lsb_release -sc
      register: result

    - name: install hashicorp deb repository
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ result.stdout }} main
        state: present
      become: true

    - name: install waypoint
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - waypoint
        - boundary
        - nomad
        - consul
